apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubetidy
spec:
  version: "v0.0.17"  # Updated version dynamically
  Homepage: https://kubetidy.io
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/PixelRobots/KubeTidy/releases/download/v0.0.17/KubeTidy-darwin-amd64-v0.0.17.tar.gz
    sha256: "your_sha256_for_darwin_amd64"
    bin: kubectl-KubeTidy
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/PixelRobots/KubeTidy/releases/download/v0.0.17/KubeTidy-darwin-arm64-v0.0.17.tar.gz
    sha256: "your_sha256_for_darwin_arm64"
    bin: kubectl-KubeTidy
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/PixelRobots/KubeTidy/releases/download/v0.0.17/KubeTidy-linux-amd64-v0.0.17.tar.gz
    sha256: "your_sha256_for_linux_amd64"
    bin: kubectl-KubeTidy
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/PixelRobots/KubeTidy/releases/download/v0.0.17/KubeTidy-linux-arm64-v0.0.17.tar.gz
    sha256: "your_sha256_for_linux_arm64"
    bin: kubectl-KubeTidy
  shortDescription: "A tool to clean up your Kubernetes config."
  description: |
    KubeTidy cleans up your Kubernetes config file by removing unreachable clusters and associated users and contexts or merging multiple config files.
    
    **Requirements:**
    - PowerShell 7 or higher must be installed.
    
    Read more documentation at: https://github.com/PixelRobots/KubeTidy
  caveats: |
    **Requirements:**
    - PowerShell 7 or higher must be installed.
