title: KubeTidy
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://docs.kubetidy.io

aux_links:
  Template Repository: https://github.com/pixelrobots/kubetidy
