title: KubeTidy
description: The docs page for KubeTidy!
theme: just-the-docs

url: https://docs.kubetidy.io

aux_links:
  Template Repository: https://github.com/pixelrobots/kubetidy

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

