name: PR Welcome Bot

on:
  pull_request_target:
    types: [opened]
    branches:
    - 'main'

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_bot:
    name: PR Bot
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.number }},
              body: 'Thank you for your contribution! 🙏 We will review your PR as soon as possible.\n The KubeTidy team'
            });