name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  pull_request:
  workflow_dispatch:


jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        run: |
          # Run ScriptAnalyzer and redirect output to a file
          Invoke-ScriptAnalyzer -Path . | Out-File -FilePath scriptAnalyzerOutput.txt

          # Append the results to the GitHub Actions summary page
          $output = Get-Content -Path scriptAnalyzerOutput.txt
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $output
        shell: pwsh