name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  pull_request:
  workflow_dispatch:

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer on PowerShell Scripts
        shell: pwsh
        run: |
          # Get all PSScript Analyzer Rules and save them in an array
          $scriptAnalyzerRules = Get-ScriptAnalyzerRule
          $Rules = @()
          $scriptAnalyzerRules | Foreach-Object { $Rules += @{"RuleName" = $_.RuleName; "Severity" = $_.Severity } }
          
          # Create an array of the types of rules
          $Severities = @("Information", "Warning", "Error")
          
          foreach ($Severity in $Severities) { 
              
              Describe "Testing PSSA $Severity Rules" -Tag $Severity {
          
                  It "<RuleName>" -TestCases ($Rules | Where-Object Severity -eq $Severity) {
                      
                      param ($RuleName)
          
                      #Test all scripts for the given rule and if there is a problem display this problem in a nice an reabable format in the debug message and let the test fail
                      Invoke-ScriptAnalyzer -Path ./ -IncludeRule $RuleName -Recurse |
                      Foreach-Object {"Problem in $($_.ScriptName) at line $($_.Line) with message: $($_.Message)" } |
                          Should -BeNullOrEmpty
                  }
              }
          }
          