name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  pull_request:
  workflow_dispatch:

jobs:
  PSScriptAnalyzer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Validate PowerShell Code
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
            path: ./
            includeDefaultRules: true
            severity: '"Error", "Warning"'
            recurse: true
            enableExit: true